platform :ios, 8.0
pod 'AFNetworking'#, '~> 2.3.1'
pod 'SDWebImage'#, '~> 3.7.1'
#pod 'UIActivityIndicator-for-SDWebImage'
pod 'Reachability'# ,'~> 3.1.1'
pod 'MBProgressHUD'#, '~> 0.9'
pod 'SVPullToRefresh'#, '~> 0.4.1'
pod 'FMDB'#, '~> 2.3'
pod 'CRGradientNavigationBar'#, '~> 0.3.2'
#pod 'Reveal-iOS-SDK', '~> 1.0.4'